Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.synced_folder ".", "/vagrant"

    config.vm.define "manager" do |manager|
         manager.vm.hostname = "manager"
        manager.vm.network "private_network", ip: "192.168.56.10"
    
        manager.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 1
            vb.name = "manager"
        end    
    end

    config.vm.define "node01" do |node|
        node.vm.hostname = "node01"
        node.vm.network "private_network", ip: "192.168.56.11"

        [8081,8082,8083,8084,8085,8086,8087].each do |port|
            node.vm.network "forwarded_port", guest: port, host: port
        end
        # node.vm.network "forwarded_port", guest: 5432, host: 5432
        # node.vm.network "forwarded_port", guest: 5672, host: 5672
        # node.vm.network "forwarded_port", guest: 15672, host: 15672
        
        node.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
            vb.name = "node01"
        end
    end

    config.vm.define "node02" do |node|
        node.vm.hostname = "node02"
        node.vm.network "private_network", ip: "192.168.56.12"
        node.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
            vb.name = "node02"
        end    
    end
end