Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.synced_folder "./", "/vagrant"
    
    config.vm.define "consulserver" do |node|
        node.vm.hostname = "consulserver"
        node.vm.network "private_network", ip: "192.168.56.10"
        node.vm.network "forwarded_port", guest: 8500, host: 8500, auto_correct: true
        node.vm.provider "virtualbox" do |vb|
            vb.memory = 512
            vb.cpus = 1
            vb.name = "consulserver"
        end
    end

    config.vm.define "api" do |node|
        node.vm.hostname = "api"
        node.vm.network "private_network", ip: "192.168.56.11"
        node.vm.network "forwarded_port", guest: 8082, host: 8082, auto_correct: true
        node.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
            vb.name = "api"
        end
    end

    config.vm.define "manager" do |node|
        node.vm.hostname = "manager"
        node.vm.network "private_network", ip: "192.168.56.12"
        node.vm.provider "virtualbox" do |vb|
            vb.memory = 256
            vb.cpus = 1
            vb.name = "manager"
        end
    end

    config.vm.define "db" do |node|
        node.vm.hostname = "db"
        node.vm.network "private_network", ip: "192.168.56.13"
        node.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 1
            vb.name = "db"
        end
    end
end
