Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 6144
    vb.cpus = 4
  end
  
  config.vm.define "manager01" do |manager|
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.56.10"

    #Это надо для очистки старого токена, если нужно перезапустить менеджер
    manager.vm.provision "shell", inline: <<-SHELL
     rm -f /vagrant/token
    SHELL

    manager.vm.provision "shell", path: "./install_docker.sh"
    manager.vm.provision "shell", path: "./manager_swarm.sh"
  end
  
  config.vm.define "worker01" do |worker|
    worker.vm.hostname = "worker01"
    worker.vm.network "private_network", ip: "192.168.56.11"

    # Это понадобится что бы подключать воркеры к сварм,
    # если менеджер не успевает подняться и создать токен
    worker.vm.provision "shell", inline: <<-SHELL
      for i in {1..60}; do
        if [ -f /vagrant/token ]; then
          break
        fi
        sleep 2
      done
    SHELL

    worker.vm.provision "shell", path: "./install_docker.sh"
    worker.vm.provision "shell", path: "./worker_swarm.sh"
  end

  config.vm.define "worker02" do |worker|
    worker.vm.hostname = "worker02"
    worker.vm.network "private_network", ip: "192.168.56.12"

    worker.vm.provision "shell", inline: <<-SHELL
      for i in {1..60}; do
        if [ -f /vagrant/token ]; then
          break
        fi
        sleep 2
      done
    SHELL

    worker.vm.provision "shell", path: "./install_docker.sh"
    worker.vm.provision "shell", path: "./worker_swarm.sh"
  end
end
