apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: zapunk1/s21-rabbitmq:spectrav
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: RABBIT_MQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: RABBIT_MQ_PASSWORD

